### ISSUE TITLE
Include baseblock with flightdata

### ISSUE THREAD

**Issue by Ierlandfan** [ianrenton/planesailing#2] opened 2020-11-13 10:43 UTC
Hi Ian,

I was also looking for a uncluttered frontend so I modified a script for an ESP8266 but it's not reliable.
Woudl it be a lot of work to include the baseblock from this picture? (The part that show "Type", Altitude, etc. etc.
Can you give me some pointers?

[http://irishharvest.nl/Images/PlaneSpotter.jpg](url)

**Comment by ianrenton** [comment] 2020-11-13 11:40
Closed, duplicate of #1

**Closed** 2020-11-13 11:39 UTC
